export default {
	printWidth: 80,
	tabWidth: 1,
	useTabs: true,
	semi: false,
	singleQuote: true,
	quoteProps: 'as-needed',
	jsxSingleQuote: true,
	bracketSpacing: true,
	bracketSameLine: false,
	arrowParens: 'avoid',
	vueIndentScriptAndStyle: false,
	endOfLine: 'lf',
	embeddedLanguageFormatting: 'auto',
	singleAttributePerLine: true,
}
